### PR TITLE
deps: cats / scala3

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@channingwalton WDYT?

**Comment by channingwalton** [comment]
Hi! Looks good to me!

**Comment by lancewalton** [comment]
Looks fine to me too

**Comment by ahjohannessen** [comment]
Updated the PR for Scala 3.0.0 - Would be nice to get a release :)

**Comment by channingwalton** [comment]
> Updated the PR for Scala 3.0.0 - Would be nice to get a release :)

I'll do it now.

**Review by channingwalton — APPROVED** [review]

**Comment by channingwalton** [comment]
@ahjohannessen its released: https://repo1.maven.org/maven2/com/casualmiracles/treelog-cats_3/

**Comment by ahjohannessen** [comment]
Awesome :) Thanks @channingwalton

**Pull request merged**
