### PR TITLE
build: update dependencies / scala / deprecation fixes

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@channingwalton @lancewalton WDYT? :)

**Review by channingwalton — APPROVED** [review]
LGTM, thanks!

**Comment by ahjohannessen** [comment]
Any chance of getting a release with this? :)

**Comment by channingwalton** [comment]
> Any chance of getting a release with this? :)

Yes, doing it now. Sorry I meant to earlier and forgot.

**Comment by ahjohannessen** [comment]
👍

**Comment by channingwalton** [comment]
It is done! v 1.8.1

It might take a bit of time for the release to appear.

**Comment by channingwalton** [comment]
I just confused myself a lot :D

`main` now uses cats, so this branch is dead. I've renamed it to `archive/cats`

**Comment by ahjohannessen** [comment]
Ah ok :) I see that you updated the libs in main before publishing, so we are good :)

**Comment by channingwalton** [comment]
Ah, no I did it afterwards. I’ll release again tomorrow. Sorry for the mess.

**Comment by channingwalton** [comment]
Ok _now_ I've done it. 1.8.2

**Comment by ahjohannessen** [comment]
great :)

**Pull request merged**
