### PR TITLE
bump deps to versions that support 2.13

### PR DESCRIPTION
**Pull request by bardurdam**
bump following dependencies to versions that support scala 2.13
- kindprojector to 0.10.3
- cats to 2.0.0-M4
- scalatest to 3.1.0-SNAP3

make travis compile version 2.13.0

### CODE REVIEW

**Comment by bardurdam** [comment]
@lancewalton WDYT?

**Comment by channingwalton** [comment]
Thanks for this. I’ll have a look later.

**Comment by bardurdam** [comment]
Thanks, that would be great. Perhaps publish too?

**Comment by channingwalton** [comment]
Thanks for this - sorry it took so long

**Pull request merged**
